name: vlang-build-pipeline

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup v
      uses: nocturlab/setup-vlang-action@v1.1.2
      with:
        v-version: 0.2.2
      id: v

    - name: run tests
      run: v test .
